#!/usr/bin/env php
<?php
use Bryse\Sora\Interpreter;

// Composer's autoload.
require __DIR__ . '/vendor/autoload.php';

\set_error_handler(function ($severity, $message, $file, $line) {
    throw new \ErrorException($message, 0, $severity, $file, $line);
}, E_ALL);

Interpreter::run('print "foo";');
